# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
            ],
        ),
    ]
